name: Generate Diff and Data Dict
on:
  workflow_dispatch:
  push:
jobs:
  Diff_And_Data_Dict:
    name: Generate Diff and Data Dict
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected or current branch to currentRelease dir
        uses: actions/checkout@v4
        with:
          path: currentRelease
      - name: Checkout main branch to prevRelease dir
        uses: actions/checkout@v4
        with:
          path: prevRelease
          ref: main
      - name: Checkout the usdm dictionary generator to usdm-dictionary-generator dir
        uses: actions/checkout@v4
        with:
          repository: cdisc-org/usdm-dictionary-generator
          path: usdm-dictionary-generator
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Install Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5
      - name: Get the info.version property from the previous version's API file (1.1.1 Provisional ...)
        id: prevVersion
        uses: notiz-dev/github-action-json-property@release
        with:
          path: prevRelease/Deliverables/API/USDM_API.json
          prop_path: info.version
      - name: Get the version number from the version string (1.1.1)
        id: split
        uses: winterjung/split@v2
        with:
          msg: ${{steps.prevVersion.outputs.prop}}
      - name: Save the previous and current version numbers
        run: |
          PREVIOUS_VERSION=${{steps.split.outputs._0}}
          PREVIOUS_VERSION="${PREVIOUS_VERSION//./-}"
          CURRENT_VERSION=${GITHUB_REF_NAME//release-/}
      - name: Copy the files needed by the usdm dictionary generator
        run: |
          cp prevRelease/Deliverables/UML/USDM_UML.xmi usdm-dictionary-generator/src/main/resources/prevRelease/.
          cp currentRelease/Deliverables/UML/USDM_UML.xmi usdm-dictionary-generator/src/main/resources/currentRelease/.
          cp currentRelease/Deliverables/CT/USDM_CT.xlsx usdm-dictionary-generator/src/main/resources/.
      - name: Compile and run the usdm dictionary generator
        run: |
          cd usdm-dictionary-generator
          mvn compile
          mvn exec:java -Dexec.mainClass="org.cdisc.tools.GeneratorApp" -Dexec.args="--compare-releases"
          mvn exec:java -Dexec.mainClass="org.cdisc.tools.GeneratorApp" -Dexec.args="--gen-table"
          cd ../
      - name: Copy and rename the generated dataDictionary to the current branch
        run: cp usdm-dictionary-generator/dataDictionary.MD "currentRelease/Deliverables/UML/."
      - name: If current branch is not main, copy and rename the generated diff to the current branch
        if: github.ref_name != github.event.repository.default_branch
        run: cp usdm-dictionary-generator/UML_DELTA.csv "currentRelease/Deliverables/UML/UML_DELTA_${PREVIOUS_VERSION}_${CURRENT_VERSION}.csv"
      - name: Commit and push the new files to the current branch
        run: |
          cd currentRelease
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate Diff and Data Dict"
          git push

# Running locally:
# gh act workflow_dispatch -P ubuntu-latest=catthehacker/ubuntu:act-latest --secret-file ../DDF-RA-Actions/my.secrets
